#  these are the operator are used for the checking two conditions 
name = "ram"
age = 27
if name == "ram" and age == 27:
    print("you are eligiable")
else:
    print("input incorrect")
##in and operator was used this meeans two conditions must be pass 
#######################using or operator###############
name = "ramp"
age = 27
if name == "ram" or age == 28:
    print("you are eligiable")
else:
    print("input incorrect")

#in or operator any one of the condition must me pass to pass the overall conditions 
    