# Generated by Django 5.0.3 on 2024-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
